# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: final—finetune+1
model_type: ImageRestorationModel
scale: 4
num_gpu: 2
manual_seed: 10

datasets:
  train:
    name: Flickr1024-sr-train
    type: PairedStereoImageDataset
    dataroot_gt: /data/sr/StereoSR/CVHSSR/datasets/StereoSR/patches_x4
    dataroot_lq: /data/sr/StereoSR/CVHSSR/datasets/StereoSR/patches_x4
    io_backend:
      type: disk

    gt_size_h: 512
    gt_size_w: 512
    use_hflip: true
    use_vflip: true
    use_rot: false
    flip_RGB: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Flickr1024-sr-test
    type: PairedStereoImageDataset
    dataroot_gt: /data/sr/StereoSR/CVHSSR/datasets/StereoSR/test/Overall
    dataroot_lq: /data/sr/StereoSR/CVHSSR/datasets/StereoSR/test/Overall
    io_backend:
      type: disk

# network structures
network_g:
  type: CVHSSR
  up_scale: 4
  width: 48
  num_blks: 17
  drop_path_rate: 0.1
  train_size: [1, 6, 128, 128]
  drop_out_rate: 0.

# path
path:
  pretrain_network_g: /data/sr/StereoSR/CVHSSR-CA/experiments/Final+2/models/net_g_150000.pth
  strict_load_g: true
  resume_state: ~

train:
  optim_g:
    type: Lion
    lr: !!float 1e-5
    weight_decay: !!float 0
    betas: [0.9, 0.9]

  scheduler:
    type: StepLR  # 或 ExponentialLR 或其他适合的调度器
    step_size: 10000
    gamma: 0.5  # 每个step_size，学习率乘以gamma

  total_iter: 100000
  warmup_iter: -1 # no warm up
  mixup: false

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e3
  save_img: false
  trans_num: 1

  max_minibatch: 1

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_skimage_ssim

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 1e3
  wandb:
    project: ~
    resume_id: ~
  use_tb_logger: true  # 或者 false，取决于您是否希望使用TensorBoard记录器

# dist training settings
dist_params:
  backend: nccl
  port: 29500
